// import express node pkg
const express = require('express')
const cors = require('cors');
const path = require('path');
const app = express();
const dotenv = require('dotenv');
dotenv.config();


const requestLogger = require('./utils/requestLogger');

const router = require('./routes/router');
const userRouter = require('./routes/userRouter');
const postRouter = require('./routes/postRouter');

const errorHandler = require('./utils/errorHandler');
const cookieParser = require('cookie-parser');
// connect to DB 
const db = require('./dbConnection');
const authController = require('./controllers/authController');


const port = process.env.PORT

// This middleware will allow us to read the body of the contents shared with req
app.use(express.json());
app.use(cookieParser());
app.use(cors({
    origin: 'http://localhost:3000',
    credentials: true
}))
app.use(requestLogger);

app.use('/router', router);
app.use('/user', userRouter);
app.use('/post', authController, postRouter);

// used to serve the static site generated by `npm run build` in react project
app.use('/',express.static('./build'))

app.get('*',(req,res)=>{
    res.sendFile(path.join(__dirname,'./build/index.html'))
})

// app.use('/posts',post);
// app.use('/electric',middleware)

// app.get('/', (req, res) => res.send('Hello World!'));

// app.post('/', (req, res) => {
//     // data shared by client is present in req.body
//     console.log(req.body);
//     res.send({success:true,message:"request completed"});
// });

app.use(errorHandler)
app.listen(port, () => {
    console.clear()
    console.log(`Server running on port ${port}!`)
})

